name: Deploy to IC Testnet (Local)

on:
  push:
    branches: [dev, test]
  workflow_dispatch:

jobs:
  deploy-testnet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dfx CLI (non-interactive)
      run: |
        DFX_VERSION=0.15.4
        curl -L -o dfx.tar.gz "https://github.com/dfinity/sdk/releases/download/${DFX_VERSION}/dfx-${DFX_VERSION}-x86_64-linux.tar.gz"
        tar -xvzf dfx.tar.gz
        sudo mv dfx /usr/local/bin/
        dfx --version


    - name: Start Local Replica
      run: |
        dfx start --background --clean

    - name: Deploy Canisters to Local Testnet
      run: |
        dfx deploy --network local

