name: Deploy to IC Testnet (Local)

on:
  push:
    branches: [dev, test]
  workflow_dispatch:

jobs:
  deploy-testnet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dfx CLI (non-interactive)
      run: |
        DFX_VERSION=0.15.4
        curl -L -o dfx.tar.gz https://github.com/dfinity/sdk/releases/download/0.18.0/dfx-0.18.0-x86_64-linux.tar.gz
        curl -L -o checksum https://github.com/dfinity/sdk/releases/download/0.18.0/dfx-0.18.0-x86_64-linux.tar.gz.sha256
        if [ "$(sha256sum dfx.tar.gz | awk '{ print $1}')" = "$(cat checksum | awk '{ print $1 }')" ]; then
          echo "Outputs match"
        else
          echo "Outputs do not match"
          exit 1
        fi
        tar -xvzf dfx.tar.gz
        sudo mv dfx /usr/local/bin/
        dfx --version

    - name: Start Local Replica
      run: |
        dfx start --background --clean

    - name: Install frontend dependencies
      working-directory: src/laincorp-com-frontend
      run: npm ci

    - name: Deploy Canisters to Local Testnet
      run: |
        dfx deploy laincorp-com-backend

